export type ApprovalType = "document_release" | "work_verification" | "bom_change";
export type ApprovalStatus = "PENDING" | "APPROVED" | "REJECTED" | "ESCALATED";
export type ApprovalUrgency = "LOW" | "NORMAL" | "HIGH" | "CRITICAL";

export interface MockApproval {
  id: string;
  title: string;
  description: string;
  type: ApprovalType;
  status: ApprovalStatus;
  urgency: ApprovalUrgency;
  requesterId: string;
  requesterName: string;
  approverId: string;
  approverName: string;
  linkedEntityId: string;
  linkedEntityType: string;
  linkedEntityLabel: string;
  dueDate: string;
  decisionNotes: string | null;
  decidedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export const MOCK_APPROVALS: MockApproval[] = [
  {
    id: "apr-001",
    title: "Release TM-4907 GA Drawing Rev.3",
    description:
      "General Arrangement drawing for Traction Motor TM-4907 ready for production release after design review.",
    type: "document_release",
    status: "PENDING",
    urgency: "HIGH",
    requesterId: "u-003-engineer",
    requesterName: "Shri P.K. Gupta",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "doc-001",
    linkedEntityType: "document",
    linkedEntityLabel: "CLW/ED/TM/4907/GA",
    dueDate: "2026-01-22",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-18T09:00:00Z",
    updatedAt: "2026-01-18T09:00:00Z",
  },
  {
    id: "apr-002",
    title: "Approve Bogie Frame Stress Analysis Report",
    description:
      "FEA stress analysis report for modified bogie frame design needs supervisor sign-off before prototype fabrication.",
    type: "document_release",
    status: "PENDING",
    urgency: "CRITICAL",
    requesterId: "u-006-engineer2",
    requesterName: "Smt. K. Lakshmi",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "doc-005",
    linkedEntityType: "document",
    linkedEntityLabel: "CLW/ED/BF/2201/SA",
    dueDate: "2026-01-20",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-15T14:30:00Z",
    updatedAt: "2026-01-15T14:30:00Z",
  },
  {
    id: "apr-003",
    title: "Verify Axle Box Assembly Work",
    description:
      "Work verification for axle box assembly completed on PL-2026-00000045. Quality checks required.",
    type: "work_verification",
    status: "PENDING",
    urgency: "NORMAL",
    requesterId: "u-003-engineer",
    requesterName: "Shri P.K. Gupta",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "pl-001",
    linkedEntityType: "pl",
    linkedEntityLabel: "PL-2026-00000045",
    dueDate: "2026-01-25",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-19T10:00:00Z",
    updatedAt: "2026-01-19T10:00:00Z",
  },
  {
    id: "apr-004",
    title: "BOM Change: Replace Bearing Supplier",
    description:
      "Proposed change to replace SKF bearings with NBC bearings for WAP-7 traction motor assembly BOM.",
    type: "bom_change",
    status: "PENDING",
    urgency: "HIGH",
    requesterId: "u-006-engineer2",
    requesterName: "Smt. K. Lakshmi",
    approverId: "u-001-admin",
    approverName: "Shri R.K. Sharma",
    linkedEntityId: "bom-001",
    linkedEntityType: "bom",
    linkedEntityLabel: "WAP-7 TM Assembly BOM",
    dueDate: "2026-01-23",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-17T11:00:00Z",
    updatedAt: "2026-01-17T11:00:00Z",
  },
  {
    id: "apr-005",
    title: "Release Transformer Specification Rev.B",
    description:
      "Updated transformer specification incorporating RDSO comments from previous review cycle.",
    type: "document_release",
    status: "PENDING",
    urgency: "NORMAL",
    requesterId: "u-003-engineer",
    requesterName: "Shri P.K. Gupta",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "doc-008",
    linkedEntityType: "document",
    linkedEntityLabel: "CLW/ED/TR/3100/SPEC",
    dueDate: "2026-01-28",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-20T08:30:00Z",
    updatedAt: "2026-01-20T08:30:00Z",
  },
  {
    id: "apr-006",
    title: "Verify Pantograph Installation Work",
    description:
      "Pantograph installation on loco WAP-7 #37023 completed. Clearance measurements verification needed.",
    type: "work_verification",
    status: "PENDING",
    urgency: "LOW",
    requesterId: "u-006-engineer2",
    requesterName: "Smt. K. Lakshmi",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "pl-003",
    linkedEntityType: "pl",
    linkedEntityLabel: "PL-2026-00000078",
    dueDate: "2026-01-30",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-21T07:45:00Z",
    updatedAt: "2026-01-21T07:45:00Z",
  },
  {
    id: "apr-007",
    title: "BOM Change: Add New Insulation Material",
    description:
      "Addition of Nomex 410 insulation sheets to traction motor winding BOM per revised RDSO specification.",
    type: "bom_change",
    status: "PENDING",
    urgency: "NORMAL",
    requesterId: "u-003-engineer",
    requesterName: "Shri P.K. Gupta",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "bom-002",
    linkedEntityType: "bom",
    linkedEntityLabel: "TM Winding BOM",
    dueDate: "2026-01-27",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-19T16:00:00Z",
    updatedAt: "2026-01-19T16:00:00Z",
  },
  {
    id: "apr-008",
    title: "Release Brake System Test Report",
    description:
      "Final brake system performance test report for WAP-7 modified design ready for approval.",
    type: "document_release",
    status: "APPROVED",
    urgency: "HIGH",
    requesterId: "u-003-engineer",
    requesterName: "Shri P.K. Gupta",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "doc-010",
    linkedEntityType: "document",
    linkedEntityLabel: "CLW/ED/BRK/1500/TR",
    dueDate: "2026-01-15",
    decisionNotes: "Test results are satisfactory. Approved for release to RDSO.",
    decidedAt: "2026-01-14T11:30:00Z",
    createdAt: "2026-01-10T09:00:00Z",
    updatedAt: "2026-01-14T11:30:00Z",
  },
  {
    id: "apr-009",
    title: "Verify Traction Motor Overhaul",
    description:
      "Complete overhaul of TM-4907 unit #15 per maintenance schedule. All parameters within tolerance.",
    type: "work_verification",
    status: "APPROVED",
    urgency: "NORMAL",
    requesterId: "u-006-engineer2",
    requesterName: "Smt. K. Lakshmi",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "pl-005",
    linkedEntityType: "pl",
    linkedEntityLabel: "PL-2026-00000102",
    dueDate: "2026-01-12",
    decisionNotes: "Verified. All test values within specified limits.",
    decidedAt: "2026-01-11T14:00:00Z",
    createdAt: "2026-01-08T10:00:00Z",
    updatedAt: "2026-01-11T14:00:00Z",
  },
  {
    id: "apr-010",
    title: "Reject Incorrect Wiring Diagram",
    description:
      "Wiring diagram DRG-2024-0847 contains errors in terminal block connections. Needs revision.",
    type: "document_release",
    status: "REJECTED",
    urgency: "HIGH",
    requesterId: "u-003-engineer",
    requesterName: "Shri P.K. Gupta",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "doc-003",
    linkedEntityType: "document",
    linkedEntityLabel: "DRG-2024-0847",
    dueDate: "2026-01-10",
    decisionNotes:
      "Terminal connections T5-T8 do not match updated circuit diagram. Please revise and resubmit.",
    decidedAt: "2026-01-09T16:45:00Z",
    createdAt: "2026-01-05T09:00:00Z",
    updatedAt: "2026-01-09T16:45:00Z",
  },
  {
    id: "apr-011",
    title: "BOM Change: Update Fastener Grade",
    description:
      "Upgrade all M12 fasteners from 8.8 to 10.9 grade in bogie frame BOM per RDSO directive.",
    type: "bom_change",
    status: "APPROVED",
    urgency: "CRITICAL",
    requesterId: "u-006-engineer2",
    requesterName: "Smt. K. Lakshmi",
    approverId: "u-001-admin",
    approverName: "Shri R.K. Sharma",
    linkedEntityId: "bom-003",
    linkedEntityType: "bom",
    linkedEntityLabel: "Bogie Frame BOM",
    dueDate: "2026-01-08",
    decisionNotes: "Approved. Critical safety upgrade mandated by RDSO letter dated 02-Jan-2026.",
    decidedAt: "2026-01-07T10:00:00Z",
    createdAt: "2026-01-03T09:00:00Z",
    updatedAt: "2026-01-07T10:00:00Z",
  },
  {
    id: "apr-012",
    title: "Release Coupler Drawing Set",
    description: "Complete set of coupler assembly drawings (5 sheets) for new design variant.",
    type: "document_release",
    status: "PENDING",
    urgency: "NORMAL",
    requesterId: "u-003-engineer",
    requesterName: "Shri P.K. Gupta",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "doc-012",
    linkedEntityType: "document",
    linkedEntityLabel: "CLW/ED/CPL/4500/ASM",
    dueDate: "2026-02-01",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-22T08:00:00Z",
    updatedAt: "2026-01-22T08:00:00Z",
  },
  {
    id: "apr-013",
    title: "Verify Wheel Turning Work",
    description:
      "Wheel profile turning on wheelset #WS-2026-089. Final dimensions to be verified against drawing.",
    type: "work_verification",
    status: "PENDING",
    urgency: "HIGH",
    requesterId: "u-003-engineer",
    requesterName: "Shri P.K. Gupta",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "pl-007",
    linkedEntityType: "pl",
    linkedEntityLabel: "PL-2026-00000134",
    dueDate: "2026-01-24",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-21T13:00:00Z",
    updatedAt: "2026-01-21T13:00:00Z",
  },
  {
    id: "apr-014",
    title: "BOM Change: Remove Obsolete Part",
    description:
      "Remove obsolete carbon brush holder (part CLW-CBH-001) from TM BOM. Replaced by integrated design.",
    type: "bom_change",
    status: "PENDING",
    urgency: "LOW",
    requesterId: "u-006-engineer2",
    requesterName: "Smt. K. Lakshmi",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "bom-004",
    linkedEntityType: "bom",
    linkedEntityLabel: "TM Carbon Brush Assembly BOM",
    dueDate: "2026-02-05",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-22T10:00:00Z",
    updatedAt: "2026-01-22T10:00:00Z",
  },
  {
    id: "apr-015",
    title: "Release Updated SMI for Axle Bearings",
    description:
      "Standard Maintenance Instruction updated with new lubrication intervals per vendor recommendation.",
    type: "document_release",
    status: "PENDING",
    urgency: "NORMAL",
    requesterId: "u-006-engineer2",
    requesterName: "Smt. K. Lakshmi",
    approverId: "u-002-supervisor",
    approverName: "Shri A.K. Verma",
    linkedEntityId: "doc-015",
    linkedEntityType: "document",
    linkedEntityLabel: "CLW/SMI/AXL/BRG/Rev.D",
    dueDate: "2026-02-03",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-22T14:00:00Z",
    updatedAt: "2026-01-22T14:00:00Z",
  },
  {
    id: "apr-016",
    title: "Escalated: Critical BOM Safety Deviation",
    description:
      "BOM shows non-approved brake pad material. Escalated from supervisor level due to safety implications.",
    type: "bom_change",
    status: "ESCALATED",
    urgency: "CRITICAL",
    requesterId: "u-002-supervisor",
    requesterName: "Shri A.K. Verma",
    approverId: "u-001-admin",
    approverName: "Shri R.K. Sharma",
    linkedEntityId: "bom-005",
    linkedEntityType: "bom",
    linkedEntityLabel: "Brake Assembly BOM",
    dueDate: "2026-01-21",
    decisionNotes: null,
    decidedAt: null,
    createdAt: "2026-01-20T16:00:00Z",
    updatedAt: "2026-01-20T16:00:00Z",
  },
];
