export type BomEntryType = "assembly" | "sub_assembly" | "component";
export type BomProductStatus = "draft" | "active" | "deprecated";
export type BomProductCategory = "locomotive" | "coach" | "wagon";
export type BomProductLifecycle = "development" | "production" | "maintenance" | "retired";

export interface BomEntry {
  id: string;
  productId: string;
  parentId: string | null;
  name: string;
  type: BomEntryType;
  plId: string | null;
  quantity: number;
  unit: string;
  material: string | null;
  weight: number | null;
  drawingRef: string | null;
  specifications: string | null;
  vendor: string | null;
  position: number;
  createdAt: string;
  updatedAt: string;
}

export interface BomProduct {
  id: string;
  name: string;
  code: string;
  description: string;
  version: string;
  status: BomProductStatus;
  category: BomProductCategory;
  lifecycle: BomProductLifecycle;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export const MOCK_BOM_PRODUCTS: BomProduct[] = [
  {
    id: "bom-prod-001",
    name: "WAP-7 Locomotive",
    code: "WAP7-CLW-2024",
    description: "25 kV AC single phase, 6350 HP electric locomotive for passenger service",
    version: "3.2",
    status: "active",
    category: "locomotive",
    lifecycle: "production",
    createdBy: "u-001-admin",
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-prod-002",
    name: "WAG-9 Locomotive",
    code: "WAG9-CLW-2024",
    description: "25 kV AC, 6000 HP freight locomotive with regenerative braking",
    version: "2.1",
    status: "active",
    category: "locomotive",
    lifecycle: "production",
    createdBy: "u-001-admin",
    createdAt: "2023-08-20T10:00:00Z",
    updatedAt: "2024-09-22T11:15:00Z",
  },
  {
    id: "bom-prod-003",
    name: "WAP-5 Locomotive",
    code: "WAP5-CLW-2024",
    description: "25 kV AC, 5400 HP high-speed passenger locomotive",
    version: "1.0",
    status: "draft",
    category: "locomotive",
    lifecycle: "development",
    createdBy: "u-003-engineer",
    createdAt: "2024-11-01T09:00:00Z",
    updatedAt: "2024-11-01T09:00:00Z",
  },
  {
    id: "bom-prod-004",
    name: "LHB AC 3-Tier Coach",
    code: "LHB-AC3T-2024",
    description:
      "Linke Hofmann Busch design air-conditioned 3-tier sleeper coach with anti-climbing feature",
    version: "2.0",
    status: "active",
    category: "coach",
    lifecycle: "production",
    createdBy: "u-001-admin",
    createdAt: "2023-03-15T07:30:00Z",
    updatedAt: "2024-11-10T16:45:00Z",
  },
  {
    id: "bom-prod-005",
    name: "BOXN Wagon",
    code: "BOXN-MCF-2024",
    description: "Open-top bogie freight wagon for coal and mineral transport, 22.9t tare weight",
    version: "4.1",
    status: "active",
    category: "wagon",
    lifecycle: "maintenance",
    createdBy: "u-002-supervisor",
    createdAt: "2022-01-10T06:00:00Z",
    updatedAt: "2024-08-05T09:20:00Z",
  },
  {
    id: "bom-prod-006",
    name: "WAM-4 Locomotive",
    code: "WAM4-CLW-2019",
    description: "25 kV AC, 2930 HP mixed traffic locomotive (legacy fleet)",
    version: "1.5",
    status: "deprecated",
    category: "locomotive",
    lifecycle: "retired",
    createdBy: "u-001-admin",
    createdAt: "2019-04-20T08:00:00Z",
    updatedAt: "2024-06-01T12:00:00Z",
  },
];

export const MOCK_BOM_ENTRIES: BomEntry[] = [
  // WAP-7 - Traction System
  {
    id: "bom-e-001",
    productId: "bom-prod-001",
    parentId: null,
    name: "Traction System",
    type: "assembly",
    plId: null,
    quantity: 1,
    unit: "set",
    material: null,
    weight: 12500,
    drawingRef: "CLW/WAP7/TS/GA",
    specifications: "Complete traction power conversion and drive system",
    vendor: null,
    position: 0,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-002",
    productId: "bom-prod-001",
    parentId: "bom-e-001",
    name: "Traction Motor TM-4907",
    type: "sub_assembly",
    plId: "pl-001",
    quantity: 6,
    unit: "nos",
    material: "Steel/Copper",
    weight: 2800,
    drawingRef: "CLW/ED/TM/4907/GA",
    specifications: "850 kW continuous, 1750 RPM max",
    vendor: "BHEL Bhopal",
    position: 0,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-003",
    productId: "bom-prod-001",
    parentId: "bom-e-002",
    name: "Armature Assembly",
    type: "component",
    plId: "pl-002",
    quantity: 1,
    unit: "nos",
    material: "Copper/Insulation",
    weight: 850,
    drawingRef: "CLW/ED/TM/4907/ARM",
    specifications: "Lap wound, Class H insulation",
    vendor: "BHEL Bhopal",
    position: 0,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-004",
    productId: "bom-prod-001",
    parentId: "bom-e-002",
    name: "Field Coil Set",
    type: "component",
    plId: "pl-003",
    quantity: 1,
    unit: "set",
    material: "Copper/Nomex",
    weight: 420,
    drawingRef: "CLW/ED/TM/4907/FC",
    specifications: "4 main poles + 4 interpoles",
    vendor: "BHEL Bhopal",
    position: 1,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-005",
    productId: "bom-prod-001",
    parentId: "bom-e-002",
    name: "Bearing Assembly (DE)",
    type: "component",
    plId: "pl-004",
    quantity: 1,
    unit: "nos",
    material: "Chrome Steel",
    weight: 35,
    drawingRef: "CLW/ED/TM/4907/BRG-DE",
    specifications: "NU330 cylindrical roller bearing",
    vendor: "SKF India",
    position: 2,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-006",
    productId: "bom-prod-001",
    parentId: "bom-e-001",
    name: "Transformer (Main)",
    type: "sub_assembly",
    plId: "pl-005",
    quantity: 1,
    unit: "nos",
    material: "CRGO Steel/Copper",
    weight: 8200,
    drawingRef: "CLW/WAP7/TF/GA",
    specifications: "25 kV primary, multiple secondary windings",
    vendor: "BHEL Jhansi",
    position: 1,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-007",
    productId: "bom-prod-001",
    parentId: "bom-e-006",
    name: "Core Assembly",
    type: "component",
    plId: null,
    quantity: 1,
    unit: "nos",
    material: "CRGO Silicon Steel",
    weight: 4100,
    drawingRef: "CLW/WAP7/TF/CORE",
    specifications: "M4 grade CRGO, 0.27mm lamination",
    vendor: "BHEL Jhansi",
    position: 0,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-008",
    productId: "bom-prod-001",
    parentId: "bom-e-006",
    name: "Winding Set (Primary)",
    type: "component",
    plId: null,
    quantity: 1,
    unit: "set",
    material: "OFHC Copper",
    weight: 1800,
    drawingRef: "CLW/WAP7/TF/WP",
    specifications: "Paper-oil insulated, Class A",
    vendor: "BHEL Jhansi",
    position: 1,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  // WAP-7 - Bogie Assembly
  {
    id: "bom-e-009",
    productId: "bom-prod-001",
    parentId: null,
    name: "Bogie Assembly",
    type: "assembly",
    plId: null,
    quantity: 2,
    unit: "nos",
    material: null,
    weight: 9200,
    drawingRef: "CLW/WAP7/BG/GA",
    specifications: "Co-Co bogie with flexicoil suspension",
    vendor: null,
    position: 1,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-010",
    productId: "bom-prod-001",
    parentId: "bom-e-009",
    name: "Bogie Frame",
    type: "sub_assembly",
    plId: "pl-006",
    quantity: 1,
    unit: "nos",
    material: "Structural Steel",
    weight: 4200,
    drawingRef: "CLW/WAP7/BG/FRAME",
    specifications: "Fabricated H-frame type",
    vendor: "CLW Chittaranjan",
    position: 0,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-011",
    productId: "bom-prod-001",
    parentId: "bom-e-010",
    name: "Primary Suspension Spring",
    type: "component",
    plId: "pl-007",
    quantity: 6,
    unit: "nos",
    material: "Spring Steel 60Si2MnA",
    weight: 45,
    drawingRef: "CLW/WAP7/BG/PSS",
    specifications: "Helical coil, 380 kN/m rate",
    vendor: "Meecon India",
    position: 0,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-012",
    productId: "bom-prod-001",
    parentId: "bom-e-010",
    name: "Axle Box Assembly",
    type: "component",
    plId: "pl-008",
    quantity: 6,
    unit: "nos",
    material: "Cast Steel/Chrome Steel",
    weight: 120,
    drawingRef: "CLW/WAP7/BG/AXB",
    specifications: "Cartridge type with spherical roller bearing",
    vendor: "FAG Bearings",
    position: 1,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-013",
    productId: "bom-prod-001",
    parentId: "bom-e-009",
    name: "Secondary Suspension (Flexicoil)",
    type: "sub_assembly",
    plId: null,
    quantity: 2,
    unit: "set",
    material: "Steel/Rubber",
    weight: 680,
    drawingRef: "CLW/WAP7/BG/SS",
    specifications: "Flexicoil with lateral & vertical dampers",
    vendor: "CLW Chittaranjan",
    position: 1,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  // WAP-7 - Pneumatic System
  {
    id: "bom-e-014",
    productId: "bom-prod-001",
    parentId: null,
    name: "Pneumatic System",
    type: "assembly",
    plId: null,
    quantity: 1,
    unit: "set",
    material: null,
    weight: 1800,
    drawingRef: "CLW/WAP7/PN/GA",
    specifications: "Compressed air system for brakes and auxiliaries",
    vendor: null,
    position: 2,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "bom-e-015",
    productId: "bom-prod-001",
    parentId: "bom-e-014",
    name: "Main Compressor",
    type: "sub_assembly",
    plId: "pl-009",
    quantity: 2,
    unit: "nos",
    material: "Cast Iron/Steel",
    weight: 380,
    drawingRef: "CLW/WAP7/PN/MC",
    specifications: "2-stage reciprocating, 2000 lpm FAD",
    vendor: "ELGi Equipments",
    position: 0,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-10-15T14:30:00Z",
  },
  // WAG-9 entries
  {
    id: "bom-e-101",
    productId: "bom-prod-002",
    parentId: null,
    name: "Traction System",
    type: "assembly",
    plId: null,
    quantity: 1,
    unit: "set",
    material: null,
    weight: 14200,
    drawingRef: "CLW/WAG9/TS/GA",
    specifications: "Thyristor-based traction power system",
    vendor: null,
    position: 0,
    createdAt: "2023-08-20T10:00:00Z",
    updatedAt: "2024-09-22T11:15:00Z",
  },
  {
    id: "bom-e-102",
    productId: "bom-prod-002",
    parentId: "bom-e-101",
    name: "Traction Motor HS-15250A",
    type: "sub_assembly",
    plId: "pl-010",
    quantity: 6,
    unit: "nos",
    material: "Steel/Copper",
    weight: 3100,
    drawingRef: "CLW/WAG9/TM/GA",
    specifications: "750 kW continuous, DC series motor",
    vendor: "BHEL Bhopal",
    position: 0,
    createdAt: "2023-08-20T10:00:00Z",
    updatedAt: "2024-09-22T11:15:00Z",
  },
  {
    id: "bom-e-103",
    productId: "bom-prod-002",
    parentId: "bom-e-101",
    name: "Thyristor Converter",
    type: "sub_assembly",
    plId: "pl-011",
    quantity: 2,
    unit: "nos",
    material: "Silicon/Copper/Aluminium",
    weight: 1500,
    drawingRef: "CLW/WAG9/TC/GA",
    specifications: "Asymmetric bridge, 3-phase thyristor converter",
    vendor: "ABB India",
    position: 1,
    createdAt: "2023-08-20T10:00:00Z",
    updatedAt: "2024-09-22T11:15:00Z",
  },
  {
    id: "bom-e-104",
    productId: "bom-prod-002",
    parentId: null,
    name: "Bogie Assembly (Co-Co)",
    type: "assembly",
    plId: null,
    quantity: 2,
    unit: "nos",
    material: null,
    weight: 10500,
    drawingRef: "CLW/WAG9/BG/GA",
    specifications: "High adhesion freight bogie",
    vendor: null,
    position: 1,
    createdAt: "2023-08-20T10:00:00Z",
    updatedAt: "2024-09-22T11:15:00Z",
  },
  {
    id: "bom-e-105",
    productId: "bom-prod-002",
    parentId: "bom-e-104",
    name: "Wheel Set",
    type: "component",
    plId: "pl-012",
    quantity: 6,
    unit: "nos",
    material: "Forged Steel R7",
    weight: 1650,
    drawingRef: "CLW/WAG9/BG/WS",
    specifications: "1092mm dia, IRS R-19 profile",
    vendor: "RWF Bangalore",
    position: 0,
    createdAt: "2023-08-20T10:00:00Z",
    updatedAt: "2024-09-22T11:15:00Z",
  },
  {
    id: "bom-e-106",
    productId: "bom-prod-002",
    parentId: "bom-e-104",
    name: "Traction Gear Assembly",
    type: "component",
    plId: "pl-013",
    quantity: 6,
    unit: "nos",
    material: "Case-hardened Steel",
    weight: 230,
    drawingRef: "CLW/WAG9/BG/TG",
    specifications: "Gear ratio 16:65, helical teeth",
    vendor: "Elecon Engineering",
    position: 1,
    createdAt: "2023-08-20T10:00:00Z",
    updatedAt: "2024-09-22T11:15:00Z",
  },
  // LHB Coach entries
  {
    id: "bom-e-201",
    productId: "bom-prod-004",
    parentId: null,
    name: "Underframe Assembly",
    type: "assembly",
    plId: null,
    quantity: 1,
    unit: "set",
    material: null,
    weight: 7800,
    drawingRef: "RCF/LHB/UF/GA",
    specifications: "Stainless steel integral coach underframe",
    vendor: null,
    position: 0,
    createdAt: "2023-03-15T07:30:00Z",
    updatedAt: "2024-11-10T16:45:00Z",
  },
  {
    id: "bom-e-202",
    productId: "bom-prod-004",
    parentId: "bom-e-201",
    name: "Centre Pivot Assembly",
    type: "component",
    plId: "pl-014",
    quantity: 2,
    unit: "nos",
    material: "Cast Steel",
    weight: 180,
    drawingRef: "RCF/LHB/UF/CP",
    specifications: "Spherical centre pivot for FIAT bogie",
    vendor: "Texmaco Rail",
    position: 0,
    createdAt: "2023-03-15T07:30:00Z",
    updatedAt: "2024-11-10T16:45:00Z",
  },
  {
    id: "bom-e-203",
    productId: "bom-prod-004",
    parentId: null,
    name: "Air Conditioning Unit",
    type: "sub_assembly",
    plId: "pl-015",
    quantity: 2,
    unit: "nos",
    material: "Aluminium/Copper",
    weight: 420,
    drawingRef: "RCF/LHB/AC/GA",
    specifications: "Roof-mounted packaged AC, 8.5 TR capacity",
    vendor: "Sidwal Refrigeration",
    position: 1,
    createdAt: "2023-03-15T07:30:00Z",
    updatedAt: "2024-11-10T16:45:00Z",
  },
  // BOXN Wagon entries
  {
    id: "bom-e-301",
    productId: "bom-prod-005",
    parentId: null,
    name: "Body Shell",
    type: "assembly",
    plId: null,
    quantity: 1,
    unit: "set",
    material: null,
    weight: 5200,
    drawingRef: "MCF/BOXN/BS/GA",
    specifications: "Corten steel open-top body with hinged doors",
    vendor: null,
    position: 0,
    createdAt: "2022-01-10T06:00:00Z",
    updatedAt: "2024-08-05T09:20:00Z",
  },
  {
    id: "bom-e-302",
    productId: "bom-prod-005",
    parentId: "bom-e-301",
    name: "Side Wall Panel",
    type: "component",
    plId: "pl-016",
    quantity: 2,
    unit: "nos",
    material: "Corten Steel IRS M-41",
    weight: 1100,
    drawingRef: "MCF/BOXN/BS/SW",
    specifications: "3.2mm corrugated panels, 2500mm height",
    vendor: "SAIL Bhilai",
    position: 0,
    createdAt: "2022-01-10T06:00:00Z",
    updatedAt: "2024-08-05T09:20:00Z",
  },
  {
    id: "bom-e-303",
    productId: "bom-prod-005",
    parentId: null,
    name: "CASNUB Bogie",
    type: "sub_assembly",
    plId: "pl-017",
    quantity: 2,
    unit: "nos",
    material: "Cast Steel/Spring Steel",
    weight: 4600,
    drawingRef: "MCF/BOXN/BG/GA",
    specifications: "CASNUB 22 NLC bogie, 22.9t axle load",
    vendor: "Hindustan Engineering",
    position: 1,
    createdAt: "2022-01-10T06:00:00Z",
    updatedAt: "2024-08-05T09:20:00Z",
  },
  // WAM-4 entries (retired)
  {
    id: "bom-e-401",
    productId: "bom-prod-006",
    parentId: null,
    name: "Traction Motor TAO-659",
    type: "sub_assembly",
    plId: "pl-018",
    quantity: 6,
    unit: "nos",
    material: "Steel/Copper",
    weight: 2400,
    drawingRef: "CLW/WAM4/TM/GA",
    specifications: "425 kW, DC series traction motor",
    vendor: "BHEL Bhopal",
    position: 0,
    createdAt: "2019-04-20T08:00:00Z",
    updatedAt: "2024-06-01T12:00:00Z",
  },
  {
    id: "bom-e-402",
    productId: "bom-prod-006",
    parentId: null,
    name: "Tap Changer Assembly",
    type: "assembly",
    plId: null,
    quantity: 1,
    unit: "nos",
    material: null,
    weight: 650,
    drawingRef: "CLW/WAM4/TC/GA",
    specifications: "32-step on-load tap changer",
    vendor: null,
    position: 1,
    createdAt: "2019-04-20T08:00:00Z",
    updatedAt: "2024-06-01T12:00:00Z",
  },
];
